services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-mbore}
      POSTGRES_USER: ${POSTGRES_USER:-mbore}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-mbore}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-mbore} -d ${POSTGRES_DB:-mbore}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: ./backend
    env_file:
      - ./.env
    environment:
      # fallbacks por si no existe .env
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg://mbore:mbore@db:5432/mbore}
      # permitir frontend en Nginx (8080) y Vite dev (5173)
      CORS_ORIGINS: ${CORS_ORIGINS:-http://localhost:8080,http://localhost:5173}
      API_KEY: ${API_KEY:-dev-secret-123}
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        # usados por Vite en build
        VITE_API_BASE: ${VITE_API_BASE:-http://localhost:8000}
        VITE_API_KEY: ${VITE_API_KEY:-dev-secret-123}
    depends_on:
      backend:
        condition: service_started
    ports:
      - "8080:80"

volumes:
  pgdata:
