services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: mbore
      POSTGRES_USER: mbore
      POSTGRES_PASSWORD: mbore
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mbore -d mbore"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  pgdata:
